### PR TITLE
Added support for Leonardo board.

### PR DESCRIPTION
**Pull request by dbhaig**

### CODE REVIEW

**Comment by dbhaig** [comment]
Please note that, brand new boards (clones from china) may have a different ID_SERIAL before they are programmed the first time (e.g. 'Arduino_Srl_Arduino_Leonardo'). After they have been programmed using Arduino IDE (or amake) the ID_SERIAL becomes  'Arduino_LLC_Arduino_Leonardo'

**Comment by dbhaig** [comment]
Using a modified version of the serial detection routine, the unprogrammed Leonardo boards return:
ID_SERIAL 'Arduino_Srl_Arduino_Leonardo' /dev/input/mouse0
ID_SERIAL 'Arduino_Srl_Arduino_Leonardo' /dev/input/event0
ID_SERIAL 'Arduino_Srl_Arduino_Leonardo' /dev/ttyACM0

**Comment by pavelmc** [comment]
Please take a peek on the changes in this branch and test it if possible.

https://github.com/pavelmc/amake/tree/multipleid

**Comment by pavelmc** [comment]
A mouse, a event and a tty ? All 3 from a single dev?

Please test the code in the branch "multipleid" in the mouse or event devices give us trouble we can filter it by "tty", now I wonder if the other boards (Trinket M0) shows also as a tty device... if not we are in trouble.

Cheers.

**Comment by dbhaig** [comment]
The trinket is not an issue:
ID_SERIAL 'Adafruit_Trinket_M0' /dev/ttyACM0

**Pull request closed without merging**
