### PR TITLE
Autodetect APATH, add serial device monitor feature

### PR DESCRIPTION
**Pull request by KjellMorgenstern**
Tested on ubuntu 16.04 with arduino mega 2560 (from elegoo) on /dev/ttyACM0

### CODE REVIEW

**Comment by pavelmc** [comment]
Hi @KjellMorgenstern, 

I played with this concept an it does not work, at least in ubuntu 16.04 & 18.04 when you use a downloaded copy of the Arduino IDE. (the repository one is very old, so most people will download and install a fresh one)

I'm working on an alternate way of do this.

Cheers.

**Comment by pavelmc** [comment]
Please check out and test a new branch called "aide-autodetect", this has the first working commit for real auto-detection of the Arduino IDE.

The only drawback so far is the use of "find" to locate the Arduino IDE, if you have more than one "uncompressed" copies of the Arduino IDE, then you may get the wrong one...

This night I will check this out to make a more robust detection... (maybe the install.sh script can be used to detect for sure the correct one...)

Comment, critics, patches, etc, all are welcomed.

Cheers

**Comment by pavelmc** [comment]
Hi again @KjellMorgenstern,

Please check the mentioned branch "aide-autodetect" and test it, it's working fine on this side;

I will wait for your test or comments to merge it on the master branch.

Cheers.

**Comment by KjellMorgenstern** [comment]
I am using the installation from ubuntu-umake, that comes with Arduino 1.8.5.
To make it work, I add ~/.local/share/umake/ide/arduino to my PATH.

Using find to discover the executable can be very slow. I would therefore suggest to check if the executable is already in the PATH first.

**Comment by pavelmc** [comment]
Thanks for the ubuntu-make software tip, very convenient.

I will move the PATH option on top, to speed up the process.

I will be then:
1. PATH search
2. XDG-menu search 
3. find search.

Please check on the mentioned dev branch in a few minutes and give some comments and appreciations.

Cheers.

**Comment by stdevPavelmc** [comment]
Hi, about the serial monitoring...

Searching on the web for best practices I found one that must fill all the basic needs, but only for monitoring.

It got implemented in commit 589c82e2ae57b9441199a613dddfba58ba095670 I'm testing another ways for interaction but that requires extra software (screen, minicom, etc.)

I will work on it for auto detect them or suggest to get them installed, in the mean while we fallback to just see what the serial has to say.

This solution was tested on Ubuntu 16.04.4 LTS and 18.04.1 LTS with a Uno and NodeMCU boards.

I hope this fill your expectations, so this bug pull request is closed, but you can comment.

**Comment by pavelmc** [comment]
Hi, about the serial monitoring...

Searching on the web for best practices I found one that must fill all the basic needs, but only for monitoring.

It got implemented in commit 589c82e I'm testing another ways for interaction but that requires extra software (screen, minicom, etc.)

I will work on it for auto detect them or suggest to get them installed, in the mean while we fallback to just see what the serial has to say.

This solution was tested on Ubuntu 16.04.4 LTS and 18.04.1 LTS with a Uno and NodeMCU boards.

I hope this fill your expectations, so this bug pull request is closed, but you can comment.

**Pull request closed without merging**
